### ISSUE TITLE
can i re-try your experiment again?

### ISSUE THREAD

**Issue by cha-noong** [RICE-EIC/HW-NAS-Bench#1]
First, Congratulations to the ICLR spotlight.

I now want to use a suitable backbone network on the Raspberry Pi.

In your paper, it is said that the rpi 4 was measured with tensorflow lite, but it seems that only the pytorch model is provided on your github.

Can you tell where is the tensorflow(tf lite) model for the experiment in your paper?

thank you

**Comment by licj15** [comment]
Thanks for your interest in HW-NAS-Bench!
Yes, DNN's latency on Raspi 4 is obtained with the TensorFlow Lite (TFLite) in our work. And you can access the TFLite models of NAS-Bench-201 search space in this [google drive folder](https://drive.google.com/file/d/1gYhD8AfUSz4m2e1XZTm3Mbxtr46Iz9xU/view?usp=sharing).

**Comment by cha-noong** [comment]
Thank you so much for sharing the tf_lite model.

I have one more question.

 Are the NAS-Bench-201 tflite models imported by converting the PyTorch model to TensorFlow?

If not, I wonder if there is an open-source provided by TensorFlow.
I cannot see it when I look it up.

**Comment by licj15** [comment]
Converting the PyTorch model to TensorFlow is not trivial due to one uses the NCHW format and the other uses the NHWC format by default. So I recommend rewriting the whole model definition using Keras, here is an example about ResNet ( [PyTorch version](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py), [Keras version](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/applications/resnet.py)).

**Comment by cha-noong** [comment]
Thank you for your kind answer.
Once again, congratulations on your acceptance of the ICLR paper.
