### ISSUE TITLE
Is the implementation of ProxylessNAS available?

### ISSUE THREAD

**Issue by mzsrkeen10** [RICE-EIC/HW-NAS-Bench#4]
Thank you for sharing your great work!

I'm trying to compare the results of the experiment of ProxylessNAS (Table 5) in your paper with other HW-NAS methods.
So I would like to use the same hyperparameters and experimental setup as in the paper.

On the OpenReview website, [AnonReviewer3 said](https://openreview.net/forum?id=_0kaDkv3dVf&noteId=cPaVg4LiF90), 

> It looks like the source code includes -- among other things -- (i) a reproduction of the FBNet search space, (ii) code for obtaining on-device benchmark numbers, (iii) a simple API for querying the inference times and energy usages of FBNet and NASBench-201 architectures, and (iv) implementations of the ProxylessNAS and FBNet search algorithms.

but I couldn't find the implementation of ProxylessNAS mentioned here.
Could you tell me where the implementation is, or what hyperparameters / experimental setup you used are?

**Comment by licj15** [comment]
Thanks for your interest in HW-NAS-Bench!
Because ProxylessNAS has already released its official codebase [here](https://github.com/mit-han-lab/proxylessnas), we are not considering including it in our code release currently. However, we are happy to provide more details about it.

During search, we set the total epochs as 120 (pretrain_epoch as 30), batch_size as 128, and lr 0.05.
After search, we use total epochs as 300, batch_size as 196, and lr 0.02 to train the model from scratch.

BTW, we suggest you can first try our searched architectures listed below with your training and inference code to check the implementation.

- Architecture searched when targeting Raspi 4: 'skip', 'k3_e3', 'skip', 'skip', 'skip', 'k5_e3', 'k3_e3', 'k3_e1', 'k3_e3', 'k5_e6', 'k3_e3', 'k3_e3', 'k3_e1_g2', 'k5_e6', 'k5_e1', 'k5_e1', 'k5_e1', 'k5_e3', 'k5_e1_g2', 'k5_e1', 'k5_e1', 'k5_e3'
- Architecture searched when targeting Edge GPU: 'k5_e3', 'k5_e6', 'skip', 'skip', 'skip', 'k5_e6', 'skip', 'skip', 'skip', 'k5_e6', 'skip', 'skip', 'skip', 'k3_e3', 'k3_e1', 'k5_e1', 'k3_e1', 'k5_e6', 'k5_e3', 'k5_e3', 'k5_e3', 'k5_e6'
- Architecture searched when targeting FPGA: 'k5_e1', 'k5_e3', 'skip', 'skip', 'skip', 'k5_e3', 'k3_e1', 'k3_e1_g2', 'k3_e1_g2', 'k5_e6', 'k3_e1_g2', 'k3_e1', 'k3_e1_g2', 'k5_e6', 'k5_e1_g2', 'k5_e1_g2', 'k3_e1_g2', 'k5_e3', 'k5_e1_g2', 'k5_e1_g2', 'k5_e1_g2', 'k5_e6'

Note: 'k' indicates the kernel size, 'e' indicates the expansion ratio and 'g' indicates the group number (g=1 will be ignored). Also, a more detailed visualization is shown in the attached figures.

**Comment by mzsrkeen10** [comment]
Thanks for your quick response and for sharing the details!
Following your advice, I will start by checking the training code using the searched architectures.
Thanks again for your excellent work!
