### ISSUE TITLE
about  power consumption

### ISSUE THREAD

**Issue by lswzjuer** [RICE-EIC/HW-NAS-Bench#8]
Wondering how the power consumption data for these backends is collected, can you provide some more details?

**Comment by licj15** [comment]
Thank you for your interest in our work!
For the power consumption measurement please refer to Sec. 3.2 of our paper.
Specifically, for devices with internal power rail monitors (e.g., Edge GPU), the power consumption is reported by the monitors. Otherwise, it is measured by an external power consumption monitor (e.g., https://www.amazon.com/Upgraded-Brighter-Consumption-Electricity-Protection/dp/B08ZD7YL54)
